import './globals.css'
import type { Metadata } from 'next'
import Nav from './pages/Nav'
import Footer from './pages/Footer'
import { Inter } from 'next/font/google' // 원하는 폰트 가져와서 사용하기

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="kr">
            <body className="bg-mainColor-100">
                <header>
                    <Nav />
                </header>
                <main className="pt-[80px]">{children}</main>
                <footer>
                    <Footer />
                </footer>
            </body>
        </html>
    )
}
